server:
  port: 8762
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HeQiHong/taobao
          username: HeQiHong
          password: 1628647HqH063.
          search-paths: config
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/